# Generated by Django 5.1.7 on 2025-03-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('target', models.CharField(choices=[(None, 'выберите цель'), ('30', 'Каждый день'), ('15', 'Каждые 2 дня'), ('12', '3 раза в неделю'), ('8', '2 раза в неделю'), ('4', 'Каждую неделю'), ('1', 'Каждый месяц')], max_length=16)),
            ],
        ),
    ]
