# Generated by Django 5.1.7 on 2025-03-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_date_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['date'], 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['date'], 'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата появления привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.CharField(choices=[(None, 'выберите цель'), ('30', 'Каждый день'), ('15', 'Каждые 2 дня'), ('12', '3 раза в неделю'), ('8', '2 раза в неделю'), ('4', 'Каждую неделю'), ('1', 'Каждый месяц')], max_length=16, verbose_name='Частота привычки'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата события'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='habit_tracker.habit', verbose_name='id привычки'),
        ),
    ]
