# Generated by Django 5.1.7 on 2025-03-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_of_the_situation', models.IntegerField(verbose_name='Оценка ситуации')),
                ('description', models.CharField(max_length=300, verbose_name='Описание ситуации')),
                ('conclusions', models.CharField(max_length=300, verbose_name='Выводы')),
                ('body_reaction', models.CharField(max_length=300, verbose_name='Реакция тела')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='изображение, отражающее чувства')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[(None, 'выберите эмоцию'), ('fear', 'страх'), ('apathy', 'апатия'), ('pain', 'боль'), ('negation', 'отрицание'), ('anger', 'гнев'), ('disappointment', 'разочарование'), ('sadness', 'печаль'), ('admiration', 'восхищение'), ('joy', 'радость'), ('happiness', 'счастье'), ('excitation', 'возбуждение'), ('appetence', 'влечение'), ('indifference', 'безразличие'), ('passion', 'страсть')], max_length=16)),
                ('id_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='emotional_diary.situation')),
            ],
            options={
                'unique_together': {('id_situation', 'emotion')},
            },
        ),
    ]
