# Generated by Django 5.1.7 on 2025-03-25 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emotion',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_diary.emotion')),
                ('id_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_diary.situation')),
            ],
        ),
        migrations.AddField(
            model_name='emotion',
            name='situations',
            field=models.ManyToManyField(related_name='emotions', through='emotional_diary.Connection', to='emotional_diary.situation'),
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='id_situation',
        ),
    ]
